version: "3"
services:
  backend:
    build: ./backend
    container_name: 'tp_peliculas_backend'
    command: sh -c 'python -u app.py'
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/backend
    depends_on:
      - "db"

  db:
    container_name: 'db_mongo'
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend
    container_name: 'tp_peliculas_frontend'
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - "backend"
    stdin_open: true
    tty: true